# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: SwarmNode7/pose
        pose2d: SwarmNode7/ground_pose
        child_frame_id: body
        parent_frame_id: world
